name: Build Geode Tools

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make zip

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake zip

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: List built files
        run: ls -R build

      - name: Zip binaries
        run: |
          cd build/${{ matrix.build_type }}
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell Compress-Archive -Path * -DestinationPath ../../geode-tools-${{ matrix.os }}.zip
          else
            zip -r ../../geode-tools-${{ matrix.os }}.zip *
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geode-tools-${{ matrix.os }}
          path: build/geode-tools-${{ matrix.os }}.zip
